server:
  port: 8092
spring:
  application:
    name: loans
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: ${SPRING_CONFIG_IMPORT}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, busrefresh